 

[font]
size = 14

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"
decorations_theme_variant = "none"
startup_mode = "maximized"

[window.padding]
x = 7
y = 7

[general]
live_config_reload = true
import = ["catppuccin-latte.toml"]
